# Generated by Django 2.2.6 on 2019-10-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_address', models.CharField(max_length=100)),
                ('guest_id', models.IntegerField()),
                ('guest_contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_id', models.IntegerField()),
                ('hotel_location', models.CharField(max_length=100)),
                ('hotel_contact', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
                ('hotel_email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('price', models.IntegerField()),
                ('guest_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Guest')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_manager_name', models.CharField(max_length=100)),
                ('hotel_contact_no', models.IntegerField()),
                ('hotel_manager_id', models.IntegerField()),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Hotel'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('log_in', models.DateField(auto_now_add=True)),
                ('log_out', models.DateField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
                ('is_cancelled', models.BooleanField()),
                ('guest_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Guest')),
                ('hotel_manager_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Manager')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Hotel')),
            ],
        ),
    ]
