# Generated by Django 2.2.6 on 2019-10-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
