# Generated by Django 2.2.6 on 2019-10-23 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_auto_20191021_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='log_in',
            field=models.DateField(default=datetime.date(2019, 10, 23)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='log_out',
            field=models.DateField(default=datetime.date(2019, 10, 24)),
        ),
    ]
