# Generated by Django 2.2.6 on 2019-10-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_auto_20191023_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_id',
        ),
    ]
